### ISSUE TITLE
[FEATURE] Create Project card design

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/zero-minds#11]
### Description

For the open project we need a design which shows the following information:

- Name of the project
- Name of the person you created the project
- Tech stack
- Open positions
- Who is currently working on

I am imagine the open position and techstack are like badges, which can be added and removed (with x) easily. Like, you can add tags on youtube videos for example.

### Screenshots

![Project card mockup](https://user-images.githubusercontent.com/54622834/235345158-6147c647-6e84-4fe5-ba82-b09e381e4bc2.png)

I created a first mock up on how the project cards could look like.

**Comment by parinitapatil** [comment]
is it still open

**Comment by YuriDevAT** [comment]
Yes, it is still open.

**Comment by parinitapatil** [comment]
please let me know if its available and if possible can u assign me?

**Comment by YuriDevAT** [comment]
Sure @parinitapatil I am happy, that you contribute again on this project.

**Comment by parinitapatil** [comment]
![image](https://github.com/YurisCodingClub/zero-minds/assets/119065651/fe6a4abf-5306-41bd-8b13-b971a639eb19)


Kindly let me know if any adjustments or revisions are necessary.

**Comment by parinitapatil** [comment]
Do you know about more uiux projects?

**Comment by parinitapatil** [comment]
MAM, I would greatly appreciate your feedback on the design. Please let me  know if you have any thoughts or suggestions. Thank you.
