### ISSUE TITLE
[FEATURE] Update style of Sign Up components

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/zero-minds#12]
### Description

Sign up component is not in its desired state.

Update the Sign up form under the components folder in src directory to look like the prototype under the screenshots section below.

### Screenshots

![Login - light](https://user-images.githubusercontent.com/54622834/235345540-7c638974-9da6-4f19-a876-7760dfc32f4c.png)

Find the integrated image here:
https://github.com/YuriDevAT/zero-minds/blob/main/public/login.png 

The colors used on this image should be corresponding tailwind color imports. (it doesn't matter if they are not exactly the same)

### Additional information
Current state of the sign up form
<img width="750" alt="sign up component in its current buggy state" src="https://github.com/YurisCodingClub/zero-minds/assets/54622834/fb48355f-5315-4525-820e-768637f86571">

**Comment by pragyamishra56** [comment]
Could you assign me, please?

**Comment by ankushbhardwaj408** [comment]
Hi @YuriDevAT i would like to work on this. Please assign it to me.

**Comment by pragyamishra56** [comment]
Could please address this issue with me

**Comment by YuriDevAT** [comment]
Happy to have you contributing to the project @pragyamishra56

**Comment by pragyamishra56** [comment]
@YuriDevAT  Thank you so much for the warm welcome! I'm excited to contribute to the project and look forward to working together. Let me know how I can get started on the issue you mentioned.

**Comment by pragyamishra56** [comment]
@YuriDevAT Ma'am, could you provide me with more information? You mentioned updating the login page, but could you assist me in locating the HTML and CSS files within your repository?

**Comment by YuriDevAT** [comment]
@pragyamishra56 as mentioned in the issue description, the files can be found in their corresponding folders inside the source folder. 

<img width="196" alt="Folder structure of the app" src="https://github.com/YurisCodingClub/zero-minds/assets/54622834/8525bd45-aac8-46b1-b89e-fec0bf149e3d">

❗ This application is not an HTML/CSS project but uses NextJS and Tailwind. Therefore, you will not be able to find html css files. Please check out the other projects https://github.com/YurisCodingClub/html-tag-quiz for an HTML CSS JS project.

**Comment by ankushbhardwaj408** [comment]
> Hi @YuriDevAT i would like to work on this. Please assign it to me.

Hi @YuriDevAT i am familiar with Reactjs and NextJs tech stack as earlier also i requested you to assign it to me. I am still eager to contribute to it.

**Comment by pragyamishra56** [comment]
@YuriDevAT Ma'am, could you please provide me with the website URL for ZeroMinds? I tried searching for it in my browser without success. This information would be helpful as you mentioned an update to the login page, and having the direct URL would facilitate a more targeted update.

**Comment by pragyamishra56** [comment]
@YuriDevAT Mam Updating the style of 'Sign Up' components means making changes to the visual appearance and layout of the elements involved in the sign-up process on a website or application? 
Identify Components, Analyze Current Style, Define Desired Changes

**Comment by YuriDevAT** [comment]
@pragyamishra56 Here is the link to the project https://zerominds.netlify.app/ It can also be found on the main page of the project in the sidebar on the top right. https://github.com/YurisCodingClub/zero-minds

**Comment by YuriDevAT** [comment]
> @YuriDevAT Mam Updating the style of 'Sign Up' components means making changes to the visual appearance and layout of the elements involved in the sign-up process on a website or application? Identify Components, Analyze Current Style, Define Desired Changes

Exactly. Two images are shared in the issue itself. The picture in the screenshot section is the wanted output. The screenshot in the additional information section is how the form currently looks.

On your on branch it is totally up to you where you want to import the sign-up component to be visible and makes it easier for you to work on.

**Comment by YuriDevAT** [comment]
As mentioned in the contribution guide issues are getting unassigned if no PR is raised within 2 weeks.
