### ISSUE TITLE
[FEATURE] Links do not have correct endpoint

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/zero-minds#19]
### Description

In the 3rd section of the `how it works` view are 4 links which are currently not directing to an end point. If possible (if the page already exists), link them to the right page. Otherwise let's keep them as they are.

### Screenshots

**Section**
<img width="838" alt="Links to endpoint" src="https://github.com/YurisCodingClub/zero-minds/assets/54622834/fb137da8-8f0a-4598-b42d-a4c41d3bec05">

**Comment by Nwakaego-Ego** [comment]
Please assign this to me

**Comment by RKOsvk** [comment]
hello, can you assign me to this issue?

**Comment by YuriDevAT** [comment]
Sure @Nwakaego-Ego, happy to have you contributin to the project 😄

**Comment by YuriDevAT** [comment]
Hi @Nwakaego-Ego. Are you working on this ticket? Two weeks already passed. As mentioned in the contribution guide, assignees will get unassigned when there is no progress within 2 weeks.

**Comment by Nwakaego-Ego** [comment]
Hi, @YuriDevAT I have had a lot of issues running this from my terminal, i just finally succeded, I want to jump right on it. I am very sorry about the delay
