### ISSUE TITLE
[FEATURE] Connect DB to frontend

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/zero-minds#2]
Currently there is no database for the application, where login and user information can be stored. Appwrite would the database to go for.

- [ ] Connect the DB to the frontend to be able to work with it

Links: https://appwrite.io/

**Comment by Preetraj2002** [comment]
hey @YuriDevAT i am a newbie to open source and i would love to take on this issue as it will help me learn about databases and how i could use Appwrite for this. Kindly consider assigning me this task @YuriDevAT

**Comment by Preetraj2002** [comment]
Hey !!! I would need everyone's help to decide the structure of the tables. What are the columns we are gonna add as user information. If it is just login then we could go for Auth in Appwrite.

Also if i add db to my account in appwrite then the scripts will contain my db ids which you have to replace it yourself.
Actually i have never used ts or js so its confusing for me to where to add the codes of appwrite ( a seperate file or index) @YuriDevAT

**Comment by YuriDevAT** [comment]
Hopefully someone is experienced enough to help with this issue. I myself also did work really work with DB before so I am not of much help. But I will take a look at it on the weekend.

**Comment by YuriDevAT** [comment]
**Pair Programming:** 
If you are experienced with databases please help out in form of pair programming. What does this mean? Connect each other and find a time where you both work on this issue together, and explain to @Preetraj2002 Preetaj what common steps are to connect to a database, especially when working on an open source project.

**Maintainer note:** 
As far as I experienced working with a db in an OS project, each contributor had to set up the DB locally and important data was stored in a encrypted file. I have no experience at all, so it would be for the pair programmer with more experience to explain it for everyone to understand. 🙇🏽
