### ISSUE TITLE
[FEATURE]  First checks for accessibility Homepage

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/zero-minds#20]
### Description

The home page needs to be checked on accessibility. Write your findings as a PR.

**Acceptance criteria**
- [ ] The homepage is tested in all major browsers (Firefox, Edge, Chrome, Edge)
   - [ ] The homepage is tested using a browser extension (Wave, axe Devtools, ..)
   - [ ] The homepage is tested using keyboard
   - [ ] The homepage is tested in desktop as well as in mobile view

**Comment by stevenjburrows** [comment]
I will investigate this for you if you would like to assign me to it

**Comment by YuriDevAT** [comment]
Happy to have you contributing to the project @stevenjburrows 👍🏽
