### ISSUE TITLE
[FEATURE] Create Card Component

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/zero-minds#24]
### Description

Create a card component using the style provided by one of our contributors.

https://github.com/YurisCodingClub/zero-minds/blob/main/public/project-card/design-link

### Acceptance criteria

- [ ] A vertical card component is created in the components folder.
- [ ] Basic styling is added (dummy image, three sections as shown in the image, no further components)

 💡 **Note:** the components inside the card will become own issues in the next few days.

**Comment by pragyamishra56** [comment]
@YuriDevAT Mam can I create a card component using HTML CSS tailwind or Bootstrap? could you assign me if that would be possible then?

**Comment by AviGawande** [comment]
would be glad if you assign this project and provide the expected result.

**Comment by YuriDevAT** [comment]
@AviGawande the expected result is shown following the link in the description. Is this something you think you can achieve using React and Tailwind?

**Comment by AviGawande** [comment]
I will contribute as per my knowledge.

**Comment by ankushbhardwaj408** [comment]
Hi @YuriDevAT i would like to contribute on this.Please assign it to me.

**Comment by YuriDevAT** [comment]
> @YuriDevAT Mam can I create a card component using HTML CSS tailwind or Bootstrap? could you assign me if that would be possible then?

For this project, Tailwind CSS is used.

<img width="325" alt="About section of the project showing the URL and tech stack" src="https://github.com/YurisCodingClub/zero-minds/assets/54622834/39fb40da-33b0-4e60-8725-b2410002d323">

You can find the techstack of each project in the about page, or sometimes also in the `readme` file.

**Comment by pragyamishra56** [comment]
@YuriDevAT Thank you for kind of your assistance, ma'am. Can I use HTML, CSS, and Tailwind?

**Comment by YuriDevAT** [comment]
Sure @pragyamishra56 happy to have you contributing to one of my projects again 😄

**Comment by pragyamishra56** [comment]
@YuriDevAT Thank you so much mam

**Comment by pragyamishra56** [comment]
@YuriDevAT Ma'am, as you mentioned the card style, do you want it to appear the same way on the frontend as in the example you provided?

**Comment by YuriDevAT** [comment]
@pragyamishra56 yes, the one on the left is the provided style from one of the contributors. I would suggest to only create the card itself, set a dummy picture on top and three sections below (tech stack, team open position) as well as a button. These do not need special styling. I will divide this issue in more single issues for each component inside the card.

Sorry for the inconvenience of the undetailed issue. It is my first time changing a private project to an open source one and the tickets were written for me only back then. Thanks for your patience. 🙇🏽

**Comment by pragyamishra56** [comment]
@YuriDevAT Ma'am, would you like us to recreate the card in HTML/CSS using Bootstrap or Tailwind, based on the contributor's design in the picture, or do you prefer some modifications to the card components as designed in Figma?

**Comment by YuriDevAT** [comment]
@pragyamishra56 I updated the issue description. Simply create the outer component and the section with Tailwind seen in the contributors design.

**Comment by pragyamishra56** [comment]
@YuriDevAT Alright mam as you mention here I'll do the same with under your guidance Thank you mam

**Comment by pragyamishra56** [comment]
@YuriDevAT Mam, I have structured it as you mentioned: 'I will divide this issue into more individual issues for each component inside the card.' I will show you a screenshot once it's done, and if there are additional tasks required, please let me know, Mam

##Screenshot
![Screenshot 2023-10-21 152354](https://github.com/YurisCodingClub/zero-minds/assets/115208912/0895cd52-5db0-4577-bc76-9e78f8bc7db7)

**Comment by YuriDevAT** [comment]
Great work @pragyamishra56 🔥

**Comment by pragyamishra56** [comment]
@YuriDevAT Ma'am, can I proceed with the pull request I've shared along with the screenshot? If you believe further improvements are required, please let me know Mam

**Comment by pragyamishra56** [comment]
@YuriDevAT Mam, I submitted the screenshot three days ago. Could you please review it? If further improvements are needed before creating a pull request, kindly let me know. Thank you for your assistance

**Comment by YuriDevAT** [comment]
> Great work @pragyamishra56 🔥

This comment I wrote 4 days ago was meant that it is okay. 👌🏽 
<img width="939" alt="Screenshot 2023-10-26 at 08 12 43" src="https://github.com/YurisCodingClub/zero-minds/assets/54622834/4c67bb8e-d135-4850-b441-7dc0e574f3da">

**Comment by pragyamishra56** [comment]
> > Great work @pragyamishra56 🔥
> 
> This comment I wrote 4 days ago was meant that it is okay. 👌🏽 <img alt="Screenshot 2023-10-26 at 08 12 43" width="939" src="https://user-images.githubusercontent.com/54622834/278229015-4c67bb8e-d135-4850-b441-7dc0e574f3da.png">

Thank you, ma'am. I appreciate your prompt response.
