### ISSUE TITLE
[FEATURE] Create Account view

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/zero-minds#25]
### Description

Create a compontent for the user's account.

No functionality needed, only the design with its main components like the profile pictures, the personal details and skills section as well as the main information like name, job description city, frontend backend, tools.

### Screenshots

![Account prototype](https://github.com/YurisCodingClub/zero-minds/assets/54622834/239f0f1d-749d-4d69-bec0-988fb8f5a358)

**Comment by pragyamishra56** [comment]
@YuriDevAT 
"Ma'am, could you assign me an issue? It will only require HTML, CSS, and Bootstrap, so I can resolve this issue."

**Comment by Nathanael-R** [comment]
Hi Julia, I'd love to work on this issue. Took a look at the tech stack and it's all stuff I'm used to working with

**Comment by YuriDevAT** [comment]
> @YuriDevAT "Ma'am, could you assign me an issue? It will only require HTML, CSS, and Bootstrap, so I can resolve this issue."

Thanks for your interest. The app uses Tailwind, no additional framework required.

**Comment by YuriDevAT** [comment]
Happy to have you contributing to the project, @Nathanael-R 😄
