### ISSUE TITLE
[IMPROVEMENT] Upgrade NextJS version to latest

### ISSUE THREAD

**Issue by Nathanael-R** [YurisCodingClub/zero-minds#26]
### Description

I'm not really sure if this should fall under improvement, fix or bug or should be an issue but...

Running this project from scratch as a new contributor throws an error in the console

Uncaught SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at parseModel (webpack-internal:///(:3000/app-client)/./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js:33:15)...

This is a bug in NEXTJS that has been fixed in the latest version, so updating this project's version would be helpful to new contributors.

**Comment by YuriDevAT** [comment]
I will assign this issue to you @Nathanael-R. Thanks for pointing that out!
