### ISSUE TITLE
[IMPROVEMENT] - Fix the responsiveness of website on mobile

### ISSUE THREAD

**Issue by Nathanael-R** [YurisCodingClub/zero-minds#29]
### Description

The website's pages aren't mobile responsive and the footer component is causing a screen overflow( see screenshots ).  

The most likely causes are: 
- Different paddings for different breakpoints aren't specified in the styles.
- The footer's input uses a fixed width and doesn't have the flex-wrap property

How to recreate
- Visit zerominds.netlify.app on a mobile browser

How to fix
- Adjust paddings according to screen breakpoints
- Ensure that the footer doesn't have any element with a fixed width and has a flex-wrap property in the appropriate places

This could be broken down into different issues/pull requests or left as one pull request depending on the maintainer

### Screenshots

**Landing page**
![WhatsApp Image 2023-10-21 at 13 02 43](https://github.com/YurisCodingClub/zero-minds/assets/72811283/85371f2f-ec4b-4799-ba29-552ac8625b92)

**Landing page-2**
![WhatsApp Image 2023-10-21 at 13 02 43 (1)](https://github.com/YurisCodingClub/zero-minds/assets/72811283/6cf93161-3a51-4b28-9084-4426925bb651)

**Footer component**
![WhatsApp Image 2023-10-21 at 13 02 43 (2)](https://github.com/YurisCodingClub/zero-minds/assets/72811283/a7752522-e262-4901-b0f1-098bebbd98ac)

**How it works page**
![WhatsApp Image 2023-10-21 at 13 02 44](https://github.com/YurisCodingClub/zero-minds/assets/72811283/f81112b7-b100-4cee-90ac-4de4a7a7e283)

**How it works-2**
![WhatsApp Image 2023-10-21 at 13 02 44 (4)](https://github.com/YurisCodingClub/zero-minds/assets/72811283/9c4d7b82-6789-4b23-9443-25a3d8596360)

**Marketplace**
![WhatsApp Image 2023-10-21 at 13 02 45](https://github.com/YurisCodingClub/zero-minds/assets/72811283/8b5033df-8d93-44e3-a948-47e9fb790b83)

**Gallery**
![WhatsApp Image 2023-10-21 at 13 02 45 (2)](https://github.com/YurisCodingClub/zero-minds/assets/72811283/da17fde5-c9f9-460d-9402-8d7bc93c9915)

**Comment by YuriDevAT** [comment]
Thanks for creating this issues 🔥 . Would you be interested in working on the responsiveness of the footer? If yes, simply create a new issue explicitly for footer responsiveness and tag this one to it. If you cannot assign yourself, just tag me and I will assign you to it. You can start working on it.

**Comment by pragyamishra56** [comment]
@YuriDevAT Mam and @Nathanael-R Sir would you like to me assign this issue?

**Comment by Nathanael-R** [comment]
> Thanks for creating this issues 🔥 . Would you be interested in working on the responsiveness of the footer? If yes, simply create a new issue explicitly for footer responsiveness and tag this one to it. If you cannot assign yourself, just tag me and I will assign you to it. You can start working on it.

Alright, I'm on it

**Comment by Nathanael-R** [comment]
I'm confused, what does staff only mean?
