### ISSUE TITLE
[FEATURE] Create dark mode version in Figma

### ISSUE THREAD

**Issue by YuriDevAT** [YurisCodingClub/zero-minds#7]
### Description

Create a dark mode version of the existing color palette using Figma.

**Current Color Palette:**
Primary Color
#8359E3
#D8B4FE

Secondary Color
#134E4A
#0F766E

Text Color
#111827
#4B5563

Background Color
#F8FAFC
#FFFFFF

### Screenshots

![Homepage - light version](https://user-images.githubusercontent.com/54622834/235343681-03170e48-f6e3-44d0-80ef-bb6d6dc71784.png)

### Additional information

[Download the Figma File](https://drive.google.com/file/d/1QiMkQtkp8m_KfzVLeOdU0DYR53P_f4DB/view?usp=share_link)

**Comment by parinitapatil** [comment]
Can you kindly provide me with the Figma link?

**Comment by YuriDevAT** [comment]
Nice to have to as a contributor, @parinitapatil 🥳 . You can download the figma file and work on it from the **additional information** section of the issue.

**Comment by parinitapatil** [comment]
May I please request that you share the link to the Figma file?

**Comment by YuriDevAT** [comment]
At this point, I only have the fig file to share, which can be downloaded and uploaded with the changes.

**Comment by parinitapatil** [comment]
Then I have to redign the whole page

**Comment by YuriDevAT** [comment]
What exactly is the issue with downloading the fig file?

**Comment by parinitapatil** [comment]
The file is a Google Drive file, and changes cannot be made in Figma.

**Comment by YuriDevAT** [comment]
It's true that it is a google drive file, and you should be able to download it. After downloading you can open the .fig file directly in Figma and work on it. The drive options are for everyone accessing the link to be able to download. Please let me know if it works.

**Comment by parinitapatil** [comment]
let me share th
![image](https://github.com/YurisCodingClub/zero-minds/assets/119065651/96713eca-c231-4942-8fbb-fd525c440d88)
e screenshot


![image](https://github.com/YurisCodingClub/zero-minds/assets/119065651/0d1796df-0d3c-4d8f-b9c4-9422d1be9e45)




![image](https://github.com/YurisCodingClub/zero-minds/assets/119065651/83edb299-43c5-4e3b-a302-980337c8c060)

**Comment by YuriDevAT** [comment]
You are on the right path. Do you have Figma installed? Then you can import it via the import button on the right. It also works in the Browser version of Figma.

<img width="1430" alt="Figma dashboard showing import button" src="https://github.com/YurisCodingClub/zero-minds/assets/54622834/7536759b-2aa3-467a-91b8-bfe674f4db88">

**Comment by parinitapatil** [comment]
Thank you so much it helped

**Comment by parinitapatil** [comment]
Kindly let me know if there have been any updates or changes.
