### ISSUE TITLE
[FEATURE ]Dark Mode toggle

### ISSUE THREAD

**Issue by israelmitolu** [YurisCodingClub/zero-minds#9]
### Description

The dark mode toggle on the website is not functioning properly. Users are unable to switch between light and dark modes on the website, as clicking the toggle button does not change the theme.

**Comment by kunalvirk** [comment]
Hii,

@YuriDevAT Can I contribute to this?

Thanks,
Kunal

**Comment by YuriDevAT** [comment]
A theme is created for dark mode: https://github.com/YurisCodingClub/zero-minds/blob/main/public/wireframe/dark-mode
